//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Export
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Export()
        {
            this.ExportDetails = new HashSet<ExportDetail>();
        }
    
        public string exportID { get; set; }
        public Nullable<int> exportTotalProduct { get; set; }
        public string exportTotalPrice { get; set; }
        public Nullable<System.DateTime> exportCreated { get; set; }
        public Nullable<int> exportStatus { get; set; }
        public string accountID { get; set; }
        public string paymentID { get; set; }
        public string storeID { get; set; }
        //custom
        public string productID { get; set; }
        public String productQuantity { get; set; }
        //

        public virtual Account Account { get; set; }
        public virtual PaymentMethod PaymentMethod { get; set; }
        public virtual Store Store { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExportDetail> ExportDetails { get; set; }

    }
}
